src/PostDog.Web/ViewModels/BaseFormViewModel.cs
using PostDog.Protocol.Validation;

namespace PostDog.Web.ViewModels
{
    public abstract class BaseFormViewModel
    {
        public BaseFormViewModel()
        {
            Rule = new FormValidator();
        }
        internal FormValidator Rule { get; set; }
    }
}

src/PostDog.Web/ViewModels/SetupViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using PostDog.Common.Globals;
using PostDog.Protocol.Models.Setup;
using PostDog.Web.DropDowns;

namespace PostDog.Web.ViewModels
{
    public class SetupViewModel: BaseFormViewModel, IValidatableObject
    {
        public SetupViewModel()
        {
            DataBaseSelectList = new List<SelectListItem>
            {
                CommonDropDown.PleaseSelect,
                DatabaseDropDown.Sqlite,
                DatabaseDropDown.MySql,
                DatabaseDropDown.PostgreSql,
                DatabaseDropDown.MsSql
            };
        }
        public IEnumerable<SelectListItem> DataBaseSelectList { get; set; }
        public string DatabaseProvider { get; set; }

        public bool ShowDatabaseFields => !string.IsNullOrWhiteSpace(DatabaseProvider) &&
                                          !DatabaseProvider.Equals(DatabaseDropDown.Sqlite.Value);

        public string DatabaseHost { get; set; }
        public string DatabasePort { get; set; }
        public string DatabaseUser { get; set; }
        public string DatabasePassword { get; set; }
        public string DatabaseName { get; set; }

        public string Username { get; set; }
        public string Password { get; set; }
        public string PasswordRepeat { get; set; }

        public SetupRequest GetSetupData()
        {
            return new SetupRequest
            {
                DatabaseProvider = DatabaseProvider,
                DatabaseHost = DatabaseHost,
                DatabasePort = DatabasePort,
                DatabaseUser = DatabaseUser,
                DatabaseUserPassword = DatabasePassword,
                DatabaseName = DatabaseName,
                InitialUsername = Username,
                UserPassword = Password
            };
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            Rule.For(nameof(DatabaseProvider)).NotEmpty().Verify(DatabaseProvider);

            if (!DatabaseProvider.Equals(nameof(DatabaseType.Sqlite)))
            {
                Rule.For(nameof(DatabaseHost)).NotEmpty().Verify(DatabaseHost);
                Rule.For(nameof(DatabasePort)).NotEmpty().Verify(DatabasePort);
                Rule.For(nameof(DatabaseName)).NotEmpty().Verify(DatabaseName);
                Rule.For(nameof(DatabaseUser)).NotEmpty().Verify(DatabaseUser);
                Rule.For(nameof(DatabasePassword)).NotEmpty().Verify(DatabasePassword);
            }

            Rule.For(nameof(Username)).NotEmpty().Verify(Username);
            Rule.For(nameof(Password)).NotEmpty().Verify(Password);
            Rule.For(nameof(PasswordRepeat)).NotEmpty().SameAs(Password).Verify(PasswordRepeat);

            foreach (var validationResult in Rule.ValidationResults)
            {
                yield return validationResult;
            }
        }
    }
}

src/PostDog.Web/Controllers/AuthController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PostDog.DomainModels.Entities;
using PostDog.Protocol.Models.Auth;

namespace PostDog.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public AuthController(SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        [HttpPost(nameof(Login))]
        public async Task<IActionResult> Login([FromBody] AuthenticateRequest request)
        {
            var user = await _userManager.FindByNameAsync(request.Username);
            if (user == null) return Unauthorized();

            var result = await _signInManager
                .CheckPasswordSignInAsync(user, request.Password, false);
            if (!result.Succeeded) return Unauthorized();

            return Ok();
        }

        [HttpPost(nameof(Register))]
        public async Task<IActionResult> Register([FromBody] RegisterRequest request)
        {
            // var user = _authFactory.BuildApplicationUser(request);
            //
            // var result = await _userManager.CreateAsync(user, request.Password);
            // if (!result.Succeeded) return BadRequest(result.Errors);
            //
            // return Ok(_authFactory.BuildRegisterResponse());
            return Ok();
        }
    }
}

src/PostDog.Web/Controllers/DocumentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PostDog.Protocol.Models.Documents;
using PostDog.Services.Services;

namespace PostDog.Web.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly DocumentService _documentService;
        private readonly ILogger<DocumentsController> _logger;

        public DocumentsController(DocumentService documentService, ILogger<DocumentsController> logger)
        {
            _documentService = documentService;
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index([FromQuery] DocumentRequest request)
        {
             var result = _documentService.GetPaginatedDocuments(request.SkipPages, request.PageOffset);
            return View();
        }

        [HttpGet]
        public IActionResult ShowUploadModal()
        {
            return PartialView("_uploadModal");
        }
    }
}

src/PostDog.Web/Controllers/HomeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PostDog.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET
        public async Task<IActionResult> Index()
        {
            return View("Index");
        }
    }
}

src/PostDog.Web/Controllers/ProcessController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PostDog.Web.Controllers
{
    public class ProcessController : Controller
    {
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

src/PostDog.Web/Controllers/SettingsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PostDog.Web.Controllers
{
    public class SettingsController : Controller
    {
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

src/PostDog.Web/Controllers/SetupController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PostDog.Services.Services;
using PostDog.Web.ViewModels;

namespace PostDog.Web.Controllers
{
    public class SetupController : Controller
    {
        private readonly SetupService _setupService;

        public SetupController(SetupService setupService)
        {
            _setupService = setupService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var viewModel = new SetupViewModel();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Index(SetupViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _setupService.SetupPostdog(viewModel.GetSetupData());
                return RedirectToAction("Index", "Home");
            }

            return View(viewModel);
        }
    }
}

src/PostDog.Web/Controllers/UserController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PostDog.Web.Controllers
{
    public class UserController : Controller
    {
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

src/PostDog.Web/Views/Documents/Index.cshtml
<div class="documents-page">
    <partial name="_contentHeader" />
    <partial name="_contentPanel"/>
</div>

src/PostDog.Web/Views/Documents/_contentHeader.cshtml
@{
    const string uploadId = "document-upload-id";
}

<div class="content-header">
    <div class="search-input-group">
        <input type="text" placeholder="Type to start search" class="search-input"/>
    </div>

    <div class="action-list">
        <div class="action">
            <div class="ms-Icon ms-Icon--FolderHorizontal" aria-hidden="true"></div>
        </div>

        <div class="action">
            <div class="ms-Icon ms-Icon--LightningBolt" aria-hidden="true"></div>
        </div>

        <div class="action" id="@uploadId">
            <div class="ms-Icon ms-Icon--OpenFile" aria-hidden="true"></div>
        </div>
    </div>
</div>

src/PostDog.Web/Views/Documents/_contentPanel.cshtml
<div class="content-panel">
    <table class="documents-table">
        <colgroup>
            <col/>
            <col/>
            <col/>
            <col/>
            <col/>
            <col/>
        </colgroup>
        <thead>
        <tr>
            <th>From</th>
            <th>
                Tags
                <div class="ms-Icon ms-Icon--MoreVertical"></div>
            </th>
            <th>Description</th>
            <th>Date</th>
            <th>Pages</th>
            <th>&nbsp</th>
        </tr>
        </thead>
        <tbody>

        <tr>
            <td>Amazon</td>
            <td>
                <div class="tag">Invoice</div>
            </td>
            <td>Invoice for new Samsung Galaxy</td>
            <td>2020-01-01</td>
            <td>1</td>
            <td>
                <div class="action-list">
                    <div class="action action--mini">
                        <FontIcon iconName="Edit" class="fabric-ui-icon"/>
                    </div>

                    <div class="action action--mini action--danger">
                        <FontIcon iconName={deleteState} class="fabric-ui-icon"/>
                    </div>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</div>

src/PostDog.Web/Views/Documents/_modalFields.cshtml
<label for="from-search-id">FROM</label>
<div class="search-input-group search-input-group--space">
    <input id="from-search-id" type="text" placeholder="..." class="search-input search-input--docs" list="data" />
    <datalist id="data">
        <option value="Hello"/>
    </datalist>
</div>

<label for="enter-tags-id">TAGS</label>
<div class="search-input-group search-input-group--space">
    <ul class="search-tag">
        <li>
            <span>Tag</span>
            <div class="search-tag__close"></div>
        </li>
    </ul>

    <input id="enter-tags-id" type="text" placeholder="..." class="search-input search-input--docs" list="tag-data"/>
    <datalist id="tag-data">
        <option value="value1"/>
    </datalist>
</div>

<label for="description-id">DESCRIPTION</label>
<div class="search-input-group search-input-group--space">
    <input id="description-id" type="text" placeholder="..." class="search-input search-input--docs" />
</div>

<label for="virtual-path-id">PATH</label>
<div class="search-input-group search-input-group--final">
    <div class="ms-Icon ms-Icon--FolderList" aria-hidden="true"></div>
    <i class="ms-Icon ms-Icon--List" aria-hidden="true"></i>
    <input id="virtual-path-id" type="text" placeholder="/" class="search-input search-input--docs" />
</div>

src/PostDog.Web/Views/Documents/_uploadModal.cshtml
<div class="new-document-modal">
    <div class="new-document-modal__backdrop"></div>
    <div class="new-document-modal__body">
        <div class="document-modal__close"></div>
        <h4>Create New File</h4>
        <form class="new-document-form" enctype="multipart/form-data">
            <partial name="_modalFields"/>
            <div class="drag-n-drop">
                <input type="file" multiple />
                <div class="ms-Icon ms-Icon--CloudAdd drag-n-drop__zone" aria-hidden="true"></div>
            </div>

            <div class="new-document-form__button-list">
                <button class="button">SUBMIT</button>
                <button class="button">CANCEL</button>
            </div>
        </form>
    </div>
</div>

src/PostDog.Web/Views/Home/Index.cshtml
Empty

src/PostDog.Web/Views/Process/Index.cshtml
Process! Dynamic Test

src/PostDog.Web/Views/Settings/Index.cshtml
Settings

src/PostDog.Web/Views/Setup/Index.cshtml
@using PostDog.Web.Helpers
@model PostDog.Web.ViewModels.SetupViewModel

@{
    Layout = "_SetupLayout";
}

<div class="setup-container">
    <form asp-action="Index" asp-controller="Setup" method="post">
        <div class="form-row">
            <div class="form-row__header">Database settings - Docker update Test</div>
        </div>
        <div class="form-row">
            <div class="form-row__label">
                <label for="database-select">Database type</label>
                <span class="form-row__mandatory">*</span>
            </div>
            <div class="form-row__input">
                <select id="database-select" asp-for="DatabaseProvider" asp-items="Model.DataBaseSelectList"></select>
            </div>
        </div>
        <div class="form-row form-row--validation"><span asp-validation-for="DatabaseProvider" class="form-validation-result"></span></div>

        <div class="form-row @Html.IsInvisible(Model.ShowDatabaseFields)">
            <div class="form-row__label">
                <label for="database-host">Host</label>
                <span class="form-row__mandatory">*</span>
            </div>
            <div class="form-row__input">
                <input type="text" asp-for="DatabaseHost" id="database-host">
            </div>
        </div>
        <div class="form-row form-row--validation @Html.IsInvisible(Model.ShowDatabaseFields)">
            <span asp-validation-for="DatabaseHost" class="form-validation-result"></span>
        </div>

        <div class="form-row @Html.IsInvisible(Model.ShowDatabaseFields)">
            <div class="form-row__label">
                <label for="database-port">Port</label>
                <span class="form-row__mandatory">*</span>
            </div>
            <div class="form-row__input">
                <input type="number" asp-for="DatabasePort" id="database-port">
            </div>
        </div>
        <div class="form-row form-row--validation @Html.IsInvisible(Model.ShowDatabaseFields)">
            <span asp-validation-for="DatabasePort" class="form-validation-result"></span>
        </div>

        <div class="form-row @Html.IsInvisible(Model.ShowDatabaseFields)">
            <div class="form-row__label">
                <label for="database-user">Database User</label>
                <span class="form-row__mandatory">*</span>
            </div>
            <div class="form-row__input">
                <input type="text" asp-for="DatabaseUser" id="database-user">
            </div>
        </div>
        <div class="form-row form-row--validation @Html.IsInvisible(Model.ShowDatabaseFields)">
            <span asp-validation-for="DatabaseUser" class="form-validation-result"></span>
        </div>

        <div class="form-row @Html.IsInvisible(Model.ShowDatabaseFields)">
            <div class="form-row__label">
                <label for="database-password">Database Password</label>
                <span class="form-row__mandatory">*</span>
            </div>
            <div class="form-row__input">
                <input type="password" asp-for="DatabasePassword" id="database-password">
            </div>
        </div>
        <div class="form-row form-row--validation @Html.IsInvisible(Model.ShowDatabaseFields)">
            <span asp-validation-for="DatabasePassword" class="form-validation-result"></span>
        </div>

        <div class="form-row @Html.IsInvisible(Model.ShowDatabaseFields)">
            <div class="form-row__label">
                <label for="database-name">Database Name</label>
                <span class="form-row__mandatory">*</span>
            </div>
            <div class="form-row__input">
                <input type="text" asp-for="DatabaseName" id="database-name">
            </div>
        </div>
        <div class="form-row form-row--validation @Html.IsInvisible(Model.ShowDatabaseFields)">
            <span asp-validation-for="DatabaseName" class="form-validation-result"></span>
        </div>

        <div class="form-row">
            <div class="form-row__header">Initial user</div>
        </div>
        <div class="form-row">
            <div class="form-row__label">
                <label for="setup-username">Username</label>
                <span class="form-row__mandatory">*</span>
            </div>
            <div class="form-row__input">
                <input type="text" asp-for="Username" id="setup-username">
            </div>
        </div>
        <div class="form-row form-row--validation">
            <span asp-validation-for="Username" class="form-validation-result"></span>
        </div>

        <div class="form-row">
            <div class="form-row__label">
                <label for="setup-password">Password</label>
                <span class="form-row__mandatory">*</span>
            </div>
            <div class="form-row__input">
                <input type="password" asp-for="Password" id="setup-password">
            </div>
        </div>
        <div class="form-row form-row--validation">
            <span asp-validation-for="Password" class="form-validation-result"></span>
        </div>

        <div class="form-row">
            <div class="form-row__label">
                <label for="setup-password-repeat">Password Repeat</label>
                <span class="form-row__mandatory">*</span>
            </div>
            <div class="form-row__input">
                <input type="password" asp-for="PasswordRepeat" id="setup-password-repeat">
            </div>
        </div>
        <div class="form-row form-row--validation">
            <span asp-validation-for="PasswordRepeat" class="form-validation-result"></span>
        </div>

        <div class="form-row">
            <button type="submit" class="button" id="setup-submit">Setup PostDog</button>
        </div>
    </form>
</div>

src/PostDog.Web/Views/Shared/_BaseLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="dist/fabric.min.css" >
</head>
<body>
<div class="grid-container">
    <partial name="_Navigation"/>
    <div class="main-grid">
        @RenderBody()
    </div>
</div>
<div id="placeholder" class="placeholder-dialog"></div>
</body>
</html>

src/PostDog.Web/Views/Shared/_BaseSetupLayout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>@ApplicationLabels.TITLE_POSTDOG</title>
    </head>
    <body class="setup-page">

    @RenderBody()

    </body>
</html>

src/PostDog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="dist/fabric.min.css" >
<link href="dist/main.57db12e1849d2fe328cc.css" rel="stylesheet"></head>
<body>
<div class="grid-container">
    <partial name="_Navigation"/>
    <div class="main-grid">
        @RenderBody()
    </div>
</div>
<div id="placeholder" class="placeholder-dialog"></div>
<script src="dist/runtime.b438b4ffec850315c5b9.js"></script><script src="dist/main.3c1c20747d11180ee6c1.js"></script><script src="dist/vendors.7f0c32a4819009249ff6.js"></script></body>
</html>

src/PostDog.Web/Views/Shared/_Navigation.cshtml
<nav class="sidenav-grid">
    <ul>
        <li>
            <div class="nav-area">
                <a asp-controller="Home" class="nav-logo">
                    LOGO
                </a>
            </div>
        </li>
        <li>
            <a asp-controller="Documents" isactive class="nav-button">
                <div class="nav-button">
                    <div class="nav-button__icon">
                        <div class="ms-Icon ms-Icon--Script" aria-hidden="true"></div>
                    </div>
                    <div className="nav-button__description">@ApplicationLabels.LABEL_NAV_DOCUMENTS</div>
                </div>
            </a>
        </li>
        <li>
            <a asp-controller="Process" isactive class="nav-button">
                <div class="nav-button">
                    <div class="nav-button__icon">
                        <div class="ms-Icon ms-Icon--Processing" aria-hidden="true"></div>
                    </div>
                    <div class="nav-button__description">@ApplicationLabels.LABEL_NAV_PROCESSES</div>
                </div>
            </a>
        </li>
        <li>
            <a asp-controller="User" isactive class="nav-button">
                <div class="nav-button">
                    <div class="nav-button__icon">
                        <div class="ms-Icon ms-Icon--Contact" aria-hidden="true"></div>
                    </div>
                    <div class="nav-button__description">@ApplicationLabels.LABEL_NAV_USER</div>
                </div>
            </a>
        </li>
        <li>
            <a asp-controller="Settings" isactive class="nav-button">
                <div class="nav-button">
                    <div class="nav-button__icon">
                        <div class="ms-Icon ms-Icon--Settings" aria-hidden="true"></div>
                    </div>
                    <div class="nav-button__description">@ApplicationLabels.LABEL_NAV_SETTINGS</div>
                </div>
            </a>
        </li>
    </ul>
</nav>

src/PostDog.Web/Views/Shared/_SetupLayout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>@ApplicationLabels.TITLE_POSTDOG</title>
    <link href="dist/main.57db12e1849d2fe328cc.css" rel="stylesheet"></head>
    <body class="setup-page">

    @RenderBody()

    <script src="dist/runtime.b438b4ffec850315c5b9.js"></script><script src="dist/main.3c1c20747d11180ee6c1.js"></script><script src="dist/vendors.7f0c32a4819009249ff6.js"></script></body>
</html>

src/PostDog.Web/Views/User/Index.cshtml
User